name: Execução dos testes e2e API
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  mvn-run:
    uses: EtechCursos/workflow-calls/.github/workflows/java-e2e-testes.yaml@main
    with:
      folder_allure: "allure-results"
    secrets:
      git_token: ${{ secrets.TOKEN }}
